services:
  app:
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./src:/app/src/
      - ./data:/app/data/
    environment:
        MPLCONFIGDIR: "/app/mplconfig"
        FLASK_TRAINING_API_URL: "http://fo_training-server:5000"
    depends_on:
      - db
    networks:
        - backbone
  db:
    image: postgres:latest
    restart: always
    # ports:
    #   - "5432:5432"
    environment:
      POSTGRES_USER: fo_services
      POSTGRES_PASSWORD: fo_services
      POSTGRES_DB: fo_services
    volumes:
      - db:/var/lib/postgresql/data
    networks:
        - backbone
#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: fo_pgadmin
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: "bla@fasel.com"
#      PGADMIN_DEFAULT_PASSWORD: 123
#    depends_on:
#      - db
#    ports:
#      - "8888:80"
#    volumes:
#      - pgadmin-data:/var/lib/pgadmin
#    networks:
#        - backbone

volumes:
  instance: {}
  db: {}
  pgadmin-data: {}

networks:
    backbone: {}
